name: code-test-build
on: push
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
      - name: Checkout Nodejs App
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
  test:
    needs: code
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout Repo
         uses: actions/checkout@v3
      -  name: Setup Node App
         uses: actions/setup-node@v3
      -  run: npm install
      -  run: npm test
        
      
      
